### ISSUE TITLE
RWD

### ISSUE THREAD

**Issue by wi1d5ky** [g0v/addressbook-frontend#2]
Shall we make reading on cellphone easier?
If the answer is, I think I could get the job.

// Sorry for my poor English >_<

**Comment by wi1d5ky** [comment]
https://github.com/g0v/addressbook-frontend/pull/4#

**Comment by wildskyf** [comment]
Merged

**Comment by yhsiang** [comment]
@wi1d5ky :+1:

**Comment by wildskyf** [comment]
自己的 issue 自己解XD
