### ISSUE TITLE
I can't run 'npm install'

### ISSUE THREAD

**Issue by wi1d5ky** [g0v/addressbook-frontend#3]
Just like my screenshot
![yoo](https://cloud.githubusercontent.com/assets/6042803/5843075/e4046a9a-a1e4-11e4-88e0-933a517fc903.png)

Is there anyone could help me?

**Comment by audreyt** [comment]
That actually look okay.

(The warning message suggests you to run `sudo npm i -g bower` to install it globally.)

**Comment by wi1d5ky** [comment]
I have installed bower globally... 
But it keep warn me.... Orz

**Comment by wi1d5ky** [comment]
明天再來研究這個問題XD 先去睡了

**Comment by wi1d5ky** [comment]
解決問題了XD
整個連 nodejs 都砍掉，專案重新 clone
就正常了：P
